### ISSUE TITLE
Offline PDF with images.

### ISSUE THREAD

**Issue by alexomul** [iclems/iOS-htmltopdf#11]
Is there any way to generate a pdf from a local html string that contains images saved in the "Documents" folder?

**Comment by rankers** [comment]
What was the solution with regard to using the base URL - I am still unable to get this to work even when I set my base URL to be the documents directory, I reference an image like such ```<img src="photo.png" >``` and I have the photo.png in the documents directory.

The corresponding html is working, just the pdf not showing the image.

**Comment by iclems** [comment]
Have you tried the same thing in a UIWebView to see if it displays?

**Comment by rankers** [comment]
Hmmm I have commented out the code that creates the UIWebView with an alpha of 0.0, and a tiny frame so I can take a look at the view - the image isn't showing.

I have resolved this by doing 

        NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
        NSString *documentsDirectory = [paths objectAtIndex:0];
        NSURL *imageURL = [NSURL fileURLWithPath:[documentsDirectory stringByAppendingString:@"/photo.png"]];
        NSString *html =  [NSString stringWithFormat:@"<img src=\"%@\" >", imageURL];


Which means I reference full paths instead of relative ones.

Cheers
